// This file was automatically generated by ObjectBox, do not modify

package perf

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()

	model.RegisterBinding(EntityBinding)
	model.LastEntityId(1, 1737161401460991620)

	return model
}
