package templates

import (
	"text/template"
)

var ModelTemplate = template.Must(template.New("binding").Funcs(funcMap).Parse(
	`// This file was automatically generated by ObjectBox, do not modify

package {{.Package}}

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

func CreateObjectBoxModel() (*objectbox.Model, error) {
	model, err := objectbox.NewModel()
	if err != nil {
		return nil, err
	}

	{{range $entity := .Entities -}}
	model.RegisterBinding({{$entity.Name}}Binding)
	{{end -}}
	model.LastEntityId({{.LastEntityId.GetId}}, {{.LastEntityId.GetUid}})
	{{if .LastIndexId}}model.LastIndexId({{.LastIndexId.GetId}}, {{.LastIndexId.GetUid}}){{end}}

	return model, nil
}`))
