// This file was automatically generated by ObjectBox, do not modify

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()

	model.RegisterBinding(TaskBinding)
	model.LastEntityId(1, 1306759095002958910)

	return model
}
