// This file was automatically generated by ObjectBox, do not modify

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

func CreateObjectBoxModel() (*objectbox.Model, error) {
	model, err := objectbox.NewModel()
	if err != nil {
		return nil, err
	}

	model.RegisterBinding(TaskBinding)
	model.LastEntityId(1, 1306759095002958910)

	return model, nil
}
