// This file was automatically generated by ObjectBox, do not modify

package model

import (
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type task_EntityInfo struct {
	Id  objectbox.TypeId
	Uid uint64
}

var TaskBinding = task_EntityInfo{
	Id:  1,
	Uid: 1306759095002958910,
}

var Task_ = struct {
	Id           objectbox.TypeId
	Text         objectbox.TypeId
	DateCreated  objectbox.TypeId
	DateFinished objectbox.TypeId
}{
	Id:           1,
	Text:         2,
	DateCreated:  3,
	DateFinished: 4,
}

func (task_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("Task", 1, 1306759095002958910)
	model.Property("Id", objectbox.PropertyType_Long, 1, 2193439623591184445)
	model.PropertyFlags(objectbox.PropertyFlags_ID)
	model.Property("Text", objectbox.PropertyType_String, 2, 6177929178231325611)
	model.Property("DateCreated", objectbox.PropertyType_Long, 3, 9141374017424160113)
	model.Property("DateFinished", objectbox.PropertyType_Long, 4, 8083684673086871702)
	model.EntityLastPropertyId(4, 8083684673086871702)
}

func (task_EntityInfo) GetId(entity interface{}) (uint64, error) {
	return entity.(*Task).Id, nil
}

func (task_EntityInfo) Flatten(entity interface{}, fbb *flatbuffers.Builder, id uint64) {
	ent := entity.(*Task)
	var offsetText = fbutils.CreateStringOffset(fbb, ent.Text)

	// build the FlatBuffers object
	fbb.StartObject(4)
	fbb.PrependUint64Slot(0, id, 0)
	fbb.PrependUOffsetTSlot(1, offsetText, 0)
	fbb.PrependInt64Slot(2, ent.DateCreated, 0)
	fbb.PrependInt64Slot(3, ent.DateFinished, 0)
}

func (task_EntityInfo) ToObject(bytes []byte) interface{} {
	table := &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	return &Task{
		Id:           table.GetUint64Slot(4, 0),
		Text:         fbutils.GetStringSlot(table, 6),
		DateCreated:  table.GetInt64Slot(8, 0),
		DateFinished: table.GetInt64Slot(10, 0),
	}
}

func (task_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*Task, 0, capacity)
}

func (task_EntityInfo) AppendToSlice(slice interface{}, entity interface{}) interface{} {
	return append(slice.([]*Task), entity.(*Task))
}

type TaskBox struct {
	*objectbox.Box
}

func BoxForTask(ob *objectbox.ObjectBox) *TaskBox {
	return &TaskBox{
		Box: ob.Box(1),
	}
}

func (box *TaskBox) Get(id uint64) (*Task, error) {
	entity, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if entity == nil {
		return nil, nil
	}
	return entity.(*Task), nil
}

func (box *TaskBox) GetAll() ([]*Task, error) {
	entities, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return entities.([]*Task), nil
}

func (box *TaskBox) Remove(entity *Task) (err error) {
	return box.Box.Remove(entity.Id)
}
