// Code generated by ObjectBox; DO NOT EDIT.

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(1)

	model.RegisterBinding(EntityBinding)
	model.LastEntityId(1, 3022148985475790732)

	return model
}
