// Code generated by ObjectBox; DO NOT EDIT.

package model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(1)

	model.RegisterBinding(EntityBinding)
	model.RegisterBinding(TestStringIdEntityBinding)
	model.RegisterBinding(EntityByValueBinding)
	model.LastEntityId(3, 2793387980842421409)

	return model
}
