name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04, ubuntu-latest]
        go: ["1.18", "1.19", "1.20", "1.21", "1.22", "1.23", "1.24"]
      fail-fast: false
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go "${{ matrix.go }}"
        uses: actions/setup-go@v2
        with:
          go-version: "${{ matrix.go }}"
      - run: ./build/ci.sh
